#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2013 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 6.10Release
// Tag = $Name:  $
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
   /// <summary>
   /// Implements the profile GarminProduct type as a class
   /// </summary>  
   public static class GarminProduct 
   {
      public const ushort Hrm1 = 1;
      public const ushort Axh01 = 2; // AXH01 HRM chipset
      public const ushort Axb01 = 3;
      public const ushort Axb02 = 4;
      public const ushort Hrm2ss = 5;
      public const ushort DsiAlf02 = 6;
      public const ushort Fr405 = 717; // Forerunner 405
      public const ushort Fr50 = 782; // Forerunner 50
      public const ushort Fr60 = 988; // Forerunner 60
      public const ushort DsiAlf01 = 1011;
      public const ushort Fr310xt = 1018; // Forerunner 310
      public const ushort Edge500 = 1036;
      public const ushort Fr110 = 1124; // Forerunner 110
      public const ushort Edge800 = 1169;
      public const ushort Chirp = 1253;
      public const ushort Edge200 = 1325;
      public const ushort Fr910xt = 1328;
      public const ushort Alf04 = 1341;
      public const ushort Fr610 = 1345;
      public const ushort Fr70 = 1436;
      public const ushort Fr310xt4t = 1446;
      public const ushort Amx = 1461;
      public const ushort Sdm4 = 10007; // SDM4 footpod
      public const ushort TrainingCenter = 20119;
      public const ushort Connect = 65534; // Garmin Connect website
      public const ushort Invalid = (ushort)0xFFFF;   
      
   }
}

