#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2013 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 6.10Release
// Tag = $Name:  $
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
   /// <summary>
   /// Implements the profile Manufacturer type as a class
   /// </summary>  
   public static class Manufacturer 
   {
      public const ushort Garmin = 1;
      public const ushort GarminFr405Antfs = 2; // Do not use.  Used by FR405 for ANTFS man id.
      public const ushort Zephyr = 3;
      public const ushort Dayton = 4;
      public const ushort Idt = 5;
      public const ushort Srm = 6;
      public const ushort Quarq = 7;
      public const ushort Ibike = 8;
      public const ushort Saris = 9;
      public const ushort SparkHk = 10;
      public const ushort Tanita = 11;
      public const ushort Echowell = 12;
      public const ushort DynastreamOem = 13;
      public const ushort Nautilus = 14;
      public const ushort Dynastream = 15;
      public const ushort Timex = 16;
      public const ushort Metrigear = 17;
      public const ushort Xelic = 18;
      public const ushort Beurer = 19;
      public const ushort Cardiosport = 20;
      public const ushort AAndD = 21;
      public const ushort Hmm = 22;
      public const ushort Suunto = 23;
      public const ushort ThitaElektronik = 24;
      public const ushort Gpulse = 25;
      public const ushort CleanMobile = 26;
      public const ushort PedalBrain = 27;
      public const ushort Peaksware = 28;
      public const ushort Saxonar = 29;
      public const ushort LemondFitness = 30;
      public const ushort Dexcom = 31;
      public const ushort WahooFitness = 32;
      public const ushort OctaneFitness = 33;
      public const ushort Archinoetics = 34;
      public const ushort TheHurtBox = 35;
      public const ushort CitizenSystems = 36;
      public const ushort Magellan = 37;
      public const ushort Osynce = 38;
      public const ushort Holux = 39;
      public const ushort Concept2 = 40;
      public const ushort OneGiantLeap = 42;
      public const ushort AceSensor = 43;
      public const ushort BrimBrothers = 44;
      public const ushort Xplova = 45;
      public const ushort PerceptionDigital = 46;
      public const ushort Bf1systems = 47;
      public const ushort Pioneer = 48;
      public const ushort Spantec = 49;
      public const ushort Metalogics = 50;
      public const ushort _4iiiis = 51;
      public const ushort SeikoEpson = 52;
      public const ushort SeikoEpsonOem = 53;
      public const ushort IforPowell = 54;
      public const ushort MaxwellGuider = 55;
      public const ushort StarTrac = 56;
      public const ushort Breakaway = 57;
      public const ushort AlatechTechnologyLtd = 58;
      public const ushort MioTechnologyEurope = 59;
      public const ushort Rotor = 60;
      public const ushort Geonaute = 61;
      public const ushort IdBike = 62;
      public const ushort Specialized = 63;
      public const ushort Wtek = 64;
      public const ushort PhysicalEnterprises = 65;
      public const ushort NorthPoleEngineering = 66;
      public const ushort Bkool = 67;
      public const ushort StagesCycling = 69;
      public const ushort Development = 255;
      public const ushort Actigraphcorp = 5759;
      public const ushort Invalid = (ushort)0xFFFF;   
      
   }
}

