#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2013 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 6.10Release
// Tag = $Name:  $
////////////////////////////////////////////////////////////////////////////////

#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.IO;


namespace Dynastream.Fit
{
   /// <summary>
   /// Implements the DeviceSettings profile message.
   /// </summary>  
   public class DeviceSettingsMesg : Mesg 
   {    
      #region Fields     
      #endregion

      #region Constructors                 
      public DeviceSettingsMesg() : base(Profile.mesgs[Profile.DeviceSettingsIndex])               
      {                 
      }
      
      public DeviceSettingsMesg(Mesg mesg) : base(mesg)
      {
      }
      #endregion // Constructors

      #region Methods    
      ///<summary>      
      /// Retrieves the UtcOffset field
      /// Comment: Offset from system time. Required to convert timestamp from system time to UTC.</summary>
      /// <returns>Returns nullable uint representing the UtcOffset field</returns>      
      public uint? GetUtcOffset()   
      {                
         return (uint?)GetFieldValue(1, 0, Fit.SubfieldIndexMainField);                     
      }

      /// <summary>        
      /// Set UtcOffset field
      /// Comment: Offset from system time. Required to convert timestamp from system time to UTC.</summary>
      /// <param name="utcOffset_">Nullable field value to be set</param>      
      public void SetUtcOffset(uint? utcOffset_) 
      {  
         SetFieldValue(1, 0, utcOffset_, Fit.SubfieldIndexMainField);
      }
                        
      #endregion // Methods
   } // Class
} // namespace
